swagger: '2.0'
info:
  version: "1.0.0"
  title: "Book API"
  description: "API for managing a list of books"
host: "localhost:5000"
basePath: "/"
schemes:
  - "http"
paths:
  /book:
    get:
      summary: "Get list of books"
      responses:
        200:
          description: "A list of books"
          schema:
            type: array
            items:
              $ref: "#/definitions/Book"
    post:
      summary: "Add a new book"
      parameters:
        - name: "author"
          in: "formData"
          required: true
          type: "string"
        - name: "language"
          in: "formData"
          required: true
          type: "string"
        - name: "title"
          in: "formData"
          required: true
          type: "string"
      responses:
        201:
          description: "Book created"
          schema:
            $ref: "#/definitions/Book"
  /book/{id}:
    get:
      summary: "Get a single book by ID"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "integer"
      responses:
        200:
          description: "A single book"
          schema:
            $ref: "#/definitions/Book"
        404:
          description: "Book not found"
    put:
      summary: "Update a book"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "integer"
        - name: "author"
          in: "formData"
          required: true
          type: "string"
        - name: "language"
          in: "formData"
          required: true
          type: "string"
        - name: "title"
          in: "formData"
          required: true
          type: "string"
      responses:
        200:
          description: "Book updated"
          schema:
            $ref: "#/definitions/Book"
        404:
          description: "Book not found"
    delete:
      summary: "Delete a book"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "integer"
      responses:
        200:
          description: "Book deleted"
        404:
          description: "Book not found"
definitions:
  Book:
    type: "object"
    required:
      - "id"
      - "author"
      - "language"
      - "title"
    properties:
      id:
        type: "integer"
      author:
        type: "string"
      language:
        type: "string"
      title:
        type: "string"
